-- CreateEnum
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'SALES_MANAGER', 'SALES_REPRESENTATIVE', 'ACCOUNT_MANAGER', 'SUPPORT_MANAGER', 'SUPPORT_AGENT', 'MARKETING_MANAGER', 'CONTENT_MARKETER', 'FINANCE_MANAGER', 'BILLING_SPECIALIST', 'CUSTOMER', 'VENDOR');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "permissions" JSONB,
ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'CUSTOMER';
